flowchart TD
  O1["Chest pain"]
  O2["Shortness of breath"]
  A1["Measure vitals"]
  
  classDef obs fill:#efe,stroke:#5a5;
  classDef action fill:#eef,stroke:#55f;

  class O1 obs
  class O2 obs
  class A1 action

subgraph Hypotheses
  H1["Panic attack"]
  H2["Pulmonary embolism"]
  H3["Heart Attack"]
end

