flowchart TD
  O1["Chest pain"]
  O2["Shortness of breath"]
  A1["Triage"]
  O6["Difficulty speaking"]
  O7["Anxious"]
  O8["Sweating"]
  A2["Measure vitals"]
  O3["Blood pressure: 120/80"]
  O4["Pulse: 110"]
  O5["Temperature: 37.8"]
  
  classDef obs fill:#efe,stroke:#5a5;
  classDef action fill:#eef,stroke:#55f;

  class O1 obs
  class O2 obs
  class O3 obs
  class O4 obs
  class O5 obs
  class O6 obs
  class O7 obs
  class O8 obs
  class A1 action
  class A2 action

subgraph Hypotheses
  H1["Panic attack"]
  H2["Pulmonary embolism"]
  H3["Heart Attack"]
end

