flowchart TD

  %% Initial observations
  subgraph initial["Initial complaints"]
    O1["Chest pain"]
    O2["Shortness of breath"]
  end

  %% Actions
  A1["Visual triage assessment"]
  A2["Measure vitals"]

  %% Visual triage observations (produced by A1)
  O6["Difficulty speaking in full sentences"]
  O7["Anxious"]
  O8["Sweating"]

  %% Vital sign observations (produced by A2)
  O3["Blood pressure: 150/95"]
  O4["Pulse: 110"]
  O5["Temperature: 37.8"]
  O9["Respiratory rate: 24"]
  O10["Oxygen saturation: 93%"]

  %% Hypotheses
  H1["Pulmonary embolism"]
  H2["pneumonia"]
  H3["Panic attack"]
  H4["Acute coronary syndrome"]

  %% Initial observations motivate actions
  O1 -->|motivates| A1
  O2 -->|motivates| A1

  %% Actions produce observations
  A1 -->|produces| O6
  A1 -->|produces| O7
  A1 -->|produces| O8

  A2 -->|produces| O3
  A2 -->|produces| O4
  A2 -->|produces| O5
  A2 -->|produces| O9
  A2 -->|produces| O10

  %% Observations suggest hypotheses
  %% chest pain can suggest all of these things.
  O1 -->|suggests| H1
  O1 -->|suggests| H2
  O1 -->|suggests| H4
  O1 -->|suggests| H3

  %% shortness of breath can also suggest all of these things.
  O2 -->|suggests| H1
  O2 -->|suggests| H2
  O2 -->|suggests| H4
  O2 -->|suggests| H3

  %% Observations against hypotheses


  classDef obs fill:#efe,stroke:#5a5
  classDef action fill:#eef,stroke:#55f
  classDef hyp fill:#ffd,stroke:#aa5

  class O1,O2,O3,O4,O5,O6,O7,O8,O9,O10 obs
  class A1,A2 action
  class H1,H2,H3,H4 hyp
