flowchart TD

  subgraph complaints["Initial complaints"]
    C1["Chest pain"]
    C2["Shortness of breath"]
  end

  subgraph actions["Investigative actions"]
    A1["Visual assessment"]
    A2["Measure vitals"]
  end

  C1 -->|motivates| A1
  C2 -->|motivates| A1
  C1 -->|motivates| A2
  C2 -->|motivates| A2

  subgraph observations["Observations"]
    O1["Respiratory distress"]
    O2["Tachycardia"]
    O3["Low oxygen saturation"]
  end

  A1 -->|produces| O1
  A2 -->|produces| O2
  A2 -->|produces| O3

  subgraph hypotheses["Hypotheses"]
    H1["Respiratory cause"]
    H2["Cardiac cause"]
    H3["Anxiety-related cause"]
  end

  O1 -->|supports| H1
  O1 -->|supports| H2

  O2 -->|supports| H1
  O2 -->|supports| H2
  O2 -->|supports| H3

  O3 -->|supports| H1
  O3 -->|supports| H2

  A5["Lung auscultation"]
  A6["Chest X-ray"]
  H1 --> |motivates| A5
  H1 --> |motivates| A6
  
  A3["ECG"]
  A4["Troponin test"]

  H2 -->|motiviates| A3
  H2 -->|motivates| A4


